image: node:10.24.0-alpine

variables:
  REIMAGINED_STAGING_IMAGE_NAME: sendy-docker-local.jfrog.io/vue-partner-portal-reimagined:latest_$CI_COMMIT_SHORT_SHA
stages:
  - buildpush
  - deploy

buildpush:staging:
  stage: buildpush
  tags:
    - shell
  before_script:
    - export REIMAGINED_STAGING_IMAGE_FLUX="sendy-docker-local.jfrog.io/vue-partner-portal-reimagined:dev_$(date +%Y-%m-%d-%H-%M)
  script:
    - docker build  --build-arg VUE_APP_PORTAL='sendy:partner'  --build-arg VUE_APP_PARTNER_BFF='https://partner-bff-test.sendyit.com/api/v1/' --build-arg VUE_APP_GOOGLE_CLIENT_ID='693530769708-t8ibd43rpavia989f7n95dqtcps5rt33.apps.googleusercontent.com' -t $REIMAGINED_STAGING_IMAGE_NAME -t $REIMAGINED_STAGING_IMAGE_FLUX -f Dockerfile .
    - docker push $REIMAGINED_STAGING_IMAGE_NAME
    - docker push $REIMAGINED_STAGING_IMAGE_FLUX
  only:
    - staging

deploy:staging:
  stage: deploy
  tags:
    - shell
  # before_script:
  #   - export STAGING_IMAGE_NAME="sendy-docker-local.jfrog.io/convoy:latest_$CI_COMMIT_SHORT_SHA"
  script:
    - ssh -i /home/ubuntu/keys/id_rsa -v -f -o StrictHostKeyChecking=no -l admin kubetest-master.sendyit.com "kubectl set image deploy vue-partner-portal-reimagined vue-partner-portal-reimagined=$REIMAGINED_STAGING_IMAGE_NAME"

  only:
    - staging
   
